### PR TITLE
feat: add speech recognition input handled by client

### PR DESCRIPTION
**Pull request by rkjaran**
This adds a microphone button to the widget, that uses streaming speech with
endpointing provided by speech.tiro.is or a compatible self-hosted server [1]

[1] https://github.com/tiro-is/tiro-speech-core

### CODE REVIEW

**Comment by lumpidu** [comment]
As I understand, you are adding a lot of generated protobuf code via `XXX_pb.js` files. I would propose not to add these files to this MR, but add a documentation step how to generate these oneself. Otherwise, one is relatively bound to the exact version of protobuf used here or in case of a grpc web version bump, a lot of code changes are necessary.

Could you maybe add a bit more about the intuition of the protobuf files? Do I understand it correctly, that these are interfacing against a gRPC server downstream ? Otoh, it would be nice, if the downstream server could use Envoy to proxy a restful interface against the own gRPC service, right ? Then this MR could be much thinner ...

**Comment by rkjaran** [comment]
> As I understand, you are adding a lot of generated protobuf code via `XXX_pb.js` files. I would propose not to add these files to this MR, but add a documentation step how to generate these oneself. Otherwise, one is relatively bound to the exact version of protobuf used here or in case of a grpc web version bump, a lot of code changes are necessary.

I personally don't really lean either way on this. A version mismatch of the `google-protobuf` or `@improbable-eng/grpc-web` library is not as problematic as it is with libprotobuf for C++ and having the generated files is a convenience for developers, e.g. they won't need to have `protoc`. The script to regenerate the code [dev/update-proto](https://github.com/SDiFI/rasa-webchat/pull/1/files#diff-a3137bc09f3265b400ee11ad37fad59b554b38a69499d7253f3f6c943a44c704) is referenced in package.json and runnable with `npm run update-proto`, provided that the host has `protoc` in `$PATH`. I could add some documentation on that and perhaps a hook that runs it automatically (?)
 
> Could you maybe add a bit more about the intuition of the protobuf files? Do I understand it correctly, that these are interfacing against a gRPC server downstream ? Otoh, it would be nice, if the downstream server could use Envoy to proxy a restful interface against the own gRPC service, right ? Then this MR could be much thinner ...

I am using gRPC-Web, more specifically [Improbable's implementation](https://github.com/improbable-eng/grpc-web/tree/master/go/grpcwebproxy) of it and the `*_pb_service.js` are the generated gRPC-Web client stubs. The server this connects to, [Tiro Speech Core](https://github.com/tiro-is/tiro-speech-core), already has a REST proxy for synchronous recognition (not using Envoy, though). Both Envoy's gRPC-Web and REST/JSON transcoding proxies do not support bidirectional streaming. So not useful for streaming speech.

Then the `*.d.ts` are actually unnecessary for this particular project, since it's not using TypeScript.

I'll document how to setup tiro-speech-core locally in this way separately in the other repository.

**Comment by lumpidu** [comment]
Ah client side streaming! Yes, some documentation concerning the gRPC generation would help. And I guess the server sends the stop notification for the button / microphone activity after detecting silence ?

**Comment by rkjaran** [comment]
Yes. The initial request asks for "single utterance" mode, which sends a response when the end of the utterance is detected and closes the stream once the first finalized transcript has been sent. This means that we *could* also display the the partial, and non-finalized, transcript. 

I'll add a postinstall hook for code generation that'll run when `npm install` is called, some documentation and update this patch.

**Comment by lumpidu** [comment]
Is there sth. like a timeout for the button in case it doesn't receive the end of utterances from the server ?

**Comment by rkjaran** [comment]
The button is currently conditioned on the end of the gRPC stream, not the end of utterance response. Which has a hard limit of 20 seconds.

**Pull request merged**
